# Generated by Django 3.2 on 2021-05-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='state',
            field=models.CharField(default='MG', max_length=4),
        ),
    ]
