# Generated by Django 3.2 on 2021-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_airports_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='iata',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
