# Generated by Django 3.2 on 2021-05-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0003_auto_20210503_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
