# Generated by Django 3.2 on 2021-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlapi', models.URLField()),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
                ('aircraft', models.CharField(max_length=64)),
                ('departure', models.CharField(max_length=4)),
                ('arrival', models.CharField(max_length=4)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
