# Generated by Django 3.2 on 2021-05-03 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airports', '0003_auto_20210503_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlapi', models.URLField(unique=True)),
                ('distance', models.FloatField()),
                ('price', models.FloatField()),
                ('aircraft', models.CharField(max_length=64)),
                ('time', models.IntegerField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='airports.airports')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='airports.airports')),
            ],
        ),
    ]
