# Generated by Django 3.2 on 2021-05-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='time',
            field=models.CharField(max_length=9),
        ),
    ]
